config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
  end
  root to: 'tasks#index'
  resources :tasks, :labels
  resources :users, only: %i[ new show edit create destroy ]
  resources :sessions, only: %i[ new create destroy ]
end

app/models/task.rb
class Task < ApplicationRecord
  before_validation :set_default_expired, on: %i[ create update ]
  validates :task_name, :description, :status, presence: true
  belongs_to :user
  has_many :task_labels, dependent: :destroy
  has_many :labels, through: :task_labels, source: :label
  
  require './app/orderclass/status'
  enum status: Status.options_for_enum

  require './app/orderclass/priority'
  enum priority: Priority.options_for_enum
  
  scope :search_task_name, -> (task_name) { where('task_name LIKE ?', "%#{task_name}%") }
  scope :search_status, -> (status) { where(status: status) }
  scope :search_label, -> (label_id) { joins(:task_labels).where(task_labels: {label_id: label_id}) }

  private
  def set_default_expired
    self.expired_at = Time.now if expired_at.blank?
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]

  def index
    if params[:sort_expired]
      @tasks = current_user.tasks.select(:id, :task_name, :description, :expired_at, :status, :priority, :created_at,).order(expired_at: :DESC)
    elsif params[:sort_priority]
      @tasks = current_user.tasks.select(:id, :task_name, :description, :expired_at, :status, :priority, :created_at,).order(priority: :DESC)
    else
      if params[:task].present?
        if params[:task][:task_name].present? && params[:task][:status].present?
          @tasks = current_user.tasks.search_task_name(params[:task][:task_name]).search_status(params[:task][:status]).order(created_at: :DESC)
        elsif params[:task][:task_name].present?
          @tasks = current_user.tasks.search_task_name(params[:task][:task_name]).order(created_at: :DESC)
        elsif params[:task][:status].present?
          @tasks = current_user.tasks.search_status(params[:task][:status]).order(created_at: :DESC)
        elsif params[:task][:label_id].present?
          @tasks = current_user.tasks.search_status(params[:task][:label_id])
        end
      else
        if params[:sort_expired].present?
          @tasks = current_user.tasks.select(:id, :task_name, :description, :expired_at, :status, :priority, :created_at,).order(expired_at: :DESC)
        else
          @tasks = current_user.tasks.select(:id, :task_name, :description, :expired_at, :status, :priority, :created_at,).order(created_at: :DESC)
        end
      end
    end
    @tasks = @tasks.page(params[:page]).per(3)
  end

  def show
  end

  def new
    @task = current_user.tasks.new
  end

  def edit
  end

  def create
    @task = current_user.tasks.build(task_params)
    respond_to do |format|
      if @task.save
        format.html { redirect_to task_url(@task), notice: "Task #{@task.task_name} was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to task_url(@task), notice: "Task #{@task.task_name} was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Task #{@task.task_name} was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:task_name, :description, :priority, :status, :expired_at, { label_ids: [] })
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<div class="error_unit">
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>
      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
</div>
<div class="row mt-4 mb-4">
  <div class="col-xs-12 col-md-6">
    <%= form_with(model: task, local: true) do |form| %>
      <div class="form-group field">
        <%= form.label :task_name %>
        <%= form.text_field :task_name, class: "form-control"  %>
      </div>

      <div class="form-group field">
        <%= form.label :description %>
        <%= form.text_area :description, class: "form-control"  %>
      </div>

      <div class="form-group field">
        <%= form.label :priority %>
        <%= form.select :priority, Priority.options_for_priority, {prompt: false}, class: "form-control" %>
      </div>

      <div class="form-group field">
        <%= form.label :status %>
        <%= form.select :status, Status.options_for_status, {prompt: false}, class: "form-control" %>
      </div>

      <div class="form-group field">
        <%= form.label :expired_at %>
        <%= form.datetime_select :expired_at, class: "form-control"  %>
      </div>
      
      <div class="form-check task_unit_check">
        <%= form.collection_check_boxes(:label_ids, Label.all, :id, :label_name) do |cb| %>
        <div class="form-check-label">
          <%= cb.label { cb.check_box + cb.text } %>
        </div>
        <% end %>
      </div>

      <div class="form-group ">
        <%= form.submit "Register", class: "btn btn-info" %>
      </div>
    <% end %>
  </div>
</div>

app/views/tasks/edit.html.erb
<div class="col-md-1">
</div>
<div class="col-xs-12 col-md-11">
  <div class="d-flex justify-content-center">
    <div class="p-2">
      <div class="shadow p-3 mb-5 bg-light rounded">
        <h1>Editing Task</h1>
        <%= render 'form', task: @task %>
        <br>
        <div class="d-flex align-items-end justify-content-between">
          <div class="p-2"><%= link_to 'Back', tasks_path, class:  'btn btn-outline-info' %></div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tasks/index.html.erb
<div class="col-md-1">
</div>
<div class="shadow p-3 mb-5 bg-light rounded col-xs-12 col-md-11 "> 
  <div class="">
    <h1 class="mb-3 text-center">Tasks</h1>
  </div>
  <form>
    <div class="form-row serch_unit">
      <%= form_with scope: :task, url: tasks_path, method: :get, local: true do |f|  %>
      <div class="form-group row col-md-4  status-choice mt-3">
        <%= f.label :task_name, class: "col-sm-6 status-choice " %>
        <%= f.text_field :task_name, class: "form-control col-sm-6 ml-3", placeholder: "Search .." %>
      </div>
      <div class="form-group row col-md-3 status-choice mt-3">
        <%= f.label :status, class: "status-choice col-sm-6" %>
        <%= f.select :status, Status.options_for_status, { include_blank: true }, class: "form-control form-control-sm col-sm-6 ml-3" %>
      </div>
      <div class="form-group row col-md-3 status-choice mt-3">
        <%= f.label :label, class: "status-choice col-sm-6" %>
        <%= f.select :label_id, Label.pluck(:label_name, :id), { include_blank: true }, class: "form-control form-control-sm col-sm-6 ml-3" %>
      </div>
      <div class="form-group col-md-2 text-right mt-4">
        <%= f.submit :search, class: "btn btn-outline-dark" %>      
      </div>
      <% end %>
    </div>
  </form>
  <div class="btn btn-primary new-btn  btn-sm mt-4 mb-4">
   <%= link_to 'New task', new_task_path %>
  </div>
  <table class="table table-hover shadow p-3 mb-5 bg-light rounded">
    <thead>
      <tr class="mx-2 d-inline-block text-justify">
        <th scope="col" > # </th>
        <th scope="col" >Task name</th>
        <th scope="col" >Description</th>
        <th scope="col" ><%= link_to "Priority", tasks_path(sort_priority: "true") %></th>
        <th scope="col" >Status</th>
        <th scope="col" ><%= link_to "Expired_at", tasks_path(sort_expired: "true") %></th>
        <th scope="col" >Label</th>
        <th scope="col" colspan="3"></th>
      </tr>
    </thead>
    <tbody class="mx-2 d-inline-block text-justify">
      <% @tasks.each_with_index do |task, index| %>
      <tr>
        <td class= "text-justify"><%= index +1 %></td>
        <td class= "text-justify"><%= task.task_name %></td>
        <td class= "text-justify"><%= task.description %></td>
        <td class= "text-justify priority"><%= task.priority %></td>
        <td class= "text-justify"><%= task.status %></td>
        <td class= "text-justify expired_row"><%= l(task.expired_at, format: :long) %></td>
        <td class= "text-justify">
        <% task.labels.each do |label| %>
          <div class="label_style btn btn-secondary">
           <%= label.label_name %>
          </div>
        <% end %>
        </td>
        <td><%= link_to 'Show', task_path(task.id), :class => 'btn btn-outline-info' %></td>
        <td><%= link_to 'Edit', edit_task_path(task.id), :class => 'btn btn-outline-secondary' %></td>
        <td><%= link_to 'Destroy', task_path(task.id), method: :delete, data: { confirm: 'Are you sure?' }, id: "delete_button", class: "btn btn-outline-danger delete-btn" %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <div class="p-2">
    <br>
    <%= paginate(@tasks) %>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="col-md-1">
</div>
<div class="col-xs-12 col-md-11">
  <div class="d-flex justify-content-center">
    <div class="p-2">
      <div class="shadow p-3 mb-5 bg-light rounded">
        <h1>New Task</h1>
        <%= render 'form', task: @task %>
        <br>
        <div class="d-flex align-items-end justify-content-between">
          <div class="p-2"><%= link_to 'Back', tasks_path, :class => 'btn btn-outline-info' %></div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tasks/show.html.erb
<div class="col-md-1">
</div>
<div class="col-xs-12 col-md-11 ">
  <h1 class="mb-3 d-flex justify-content-center"> Show Tasks</h1>
  <div class="shadow p-3 mb-5 bg-light rounded ">
    <div class=" justify-content-center ">
      <div class="justify-content-center text-justify">
        <strong>Task name:</strong>
        <%= @task.task_name %>
      </div>
      <div class="justify-content-center text-justify">
          <strong>Description:</strong>
          <%= @task.description %>
      </div>
      <div class="justify-content-center text-justify">
          <strong>Priority:</strong>
          <%= @task.priority %>
      </div>
      <div class="justify-content-center text-justify">
          <strong>Status:</strong>
          <%= @task.status %>
      </div>
      <div class="justify-content-center text-justify">
          <strong>Expired_at:</strong>
          <%= l @task.expired_at, format: :long %>
      </div>
      <% @task.labels.each do |label| %>
      <div class="btn btn-secondary" id="label_show">
        <%= label.label_name %>
      </div>
      <% end %> 
      </div>
    </div>
    <br>
    <div class="d-flex align-items-end justify-content-between">
      <div class="justify-content-center text-justify"><%= link_to 'Edit', edit_task_path(@task.id), :class => 'btn btn-outline-info' %></div>
      <div class="justify-content-center text-justify"><%= link_to 'Back', tasks_path(@task.id), :class => 'btn btn-outline-info' %></div>
    </div>
  </div>
</div>