config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
  end
  root to: 'tasks#index'
  resources :tasks, :labels
  resources :users, only: %i[ new show edit create destroy ]
  resources :sessions, only: %i[ new create destroy ]
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :user_name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, uniqueness: true, length: {maximum: 255 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :password, length: { minimum: 6 }
  before_validation { email.downcase! }
  has_many :tasks, dependent: :destroy
  after_update :ensure_admin
  after_destroy :ensure_admin

  private
  def ensure_admin
    if User.where(admin: true).count.zero?
      raise "Last administrator cannot be deleted"
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :require_admin
  skip_before_action :login_required
  
  def index
    @users = User.select(:id, :user_name, :email, :admin,).order(created_at: :DESC)
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_user_path(@user)
      flash[:success] = "User「#{@user.user_name}」has been created"
    else
      render :new
    end
  end
  
  def show
  end
  
  def edit
  end
  
  def update
    begin
      if @user.update(user_params)
        redirect_to admin_user_path(@user)
        flash[:info] = "User「#{@user.user_name}」has been edited"
      else
        render :edit
      end
    rescue RuntimeError
      redirect_to edit_admin_user_path(@user)
      flash[:warning] = "Only administer has privilege for editing"
    end
  end
  def destroy
    unless @user == current_user
          @user.destroy
          redirect_to admin_users_path
          flash[:danger] = "User「#{@user.user_name}」has been deleted"
    else
        redirect_to admin_users_path
        flash[:warning] = "This administer can no be delete it"
    end
  end
  private
  def user_params
    params.require(:user).permit(:user_name, :email, :admin, :password, :password_confirmation,)
  end
  def set_user
    @user = User.find(params[:id])
  end
  def require_admin
    unless current_user.admin?
      redirect_to root_url
      flash[:warning] = "Only administrator users can access"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  skip_before_action :login_required, only: %i[ new create ]
  
  def index
  end
  
  def new
    if logged_in?
      redirect_to user_path(current_user.id)
    else
      @user = User.new
    end
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user.id)
      flash.now[:success] = "User「#{@user.user_name}」has been created"
    else
      render :new
    end
  end
  
  def show
    if @user.id == current_user.id || current_user.admin?
      @tasks = current_user.tasks.select(:id, :task_name, :description, :expired_at, :status, :priority, :created_at,).order("created_at DESC")
    else
      redirect_to tasks_path
    end
  end
    
  def edit
  end
    
  def update
    if @user.update(user_params)
      redirect_to user_path(@user.id)
      flash.now[:success] = "User「#{@user.user_name}」has been updated"
    else
      render :edit
    end
  end
  
  def destroy
    @user.destroy
    redirect_to new_user_path
    flash[:notice] = "User #{@user.user_name} has been Deleted"
  end
  
  private
  def user_params
    params.require(:user).permit(:user_name, :email, :password, :password_confirmation, :admin)
  end
  def set_user
    @user = User.find(params[:id])
  end
end
  

app/views/admin/users/edit.html.erb
<div class="col-md-1">
</div>
<div class="col-xs-12 col-md-6">
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.user_name %> from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <h1 class="mb-3">User edit screen</h1>
  <div class="">
    <%= form_with(model: [:admin, @user], local: true) do |f| %>
    <div class="form-group">
      <%= f.label :user_name %>
      <%= f.text_field :user_name, class: "form-control", placeholder: "Surname Lastname" %>
    </div>
    <div class="form-group">
      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control", placeholder: " xxx@mail.com" %>
    </div>
    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control", placeholder: "6 digits or more" %>
    </div>
    <div class="form-group">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: "form-control", placeholder: "confirm your password" %>
    </div>
    <div class="form-check">
      <%= f.check_box :admin, class: "form-check-input" %>
      <%= f.label :admin, class: "form-check-label" %>
    </div>
    <div class="form-group mt-3">
      <%= f.submit "Register", class: "btn btn-info" %>
    </div>
    <% end %>
  </div>
</div>
<div class="col-md-5">
</div>

app/views/admin/users/index.html.erb
<div class="col-md-1">
</div>
<div class="col-xs-12 col-md-11">
  <div class="">
    <h1 class="mb-3">User Managment List</h1>
  </div>
  <div class="btn btn-primary new-btn  btn-sm mb-4">
    <%= link_to 'New user', new_admin_user_path %>
  </div>
  <div class="btn btn-primary new-btn  btn-sm mb-4">
    <%= link_to 'New label', new_label_path %>
  </div>
  <table class="table">
    <thead>
      <th class= "text-justify"> Name </th>
      <th class= "text-justify"> Email </th>
      <th class= "text-justify"> Privilage Admin </th>
      <th class= "text-justify"><%= "" %></th>
    </thead>
    <tbody>
      <% @users.each do |user| %>
      <tr class="user_management">
        <td class= "text-justify"><%= user.user_name %></td>
        <td class= "text-justify"><%= user.email %></td>
        <td class= "text-justify"><%= user.admin? ? 'Admin' : 'none' %></td>
        <td class= "text-justify">
          <%= link_to "Show", admin_user_path(user.id),  class: "btn btn-outline-primary show-btn" %>
          <%= link_to "Edit", edit_admin_user_path(user.id), class: "btn btn-outline-success edit-btn" %>
          <%= link_to "Delete", admin_user_path(user.id), method: :delete, data: {confirm: "User「#{user.user_name}」will be delete, Are you sure?'"}, id: "delete_button", class: "btn btn-outline-danger delete-btn" %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/users/new.html.erb
<div class="col-md-1">
</div>
<div class="col-xs-12 col-md-6">
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.user_name %> from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <h1 class="mb-3">User Managment register</h1>
  <div class="">
    <%= form_with(model: [:admin, @user], local: true) do |f| %>
    <div class="form-group">
      <%= f.label :user_name %>
      <%= f.text_field :user_name, class: "form-control", placeholder: "Surname Last name" %>
    </div>
    <div class="form-group">
      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control", placeholder: " xxx@mail.com" %>
    </div>
    <div class="form-group">
      <%= f.label :password, t('view.password') %>
      <%= f.password_field :password, class: "form-control", placeholder: "6 or more characters" %>
    </div>
    <div class="form-group">
      <%= f.label :password_confirmation, t('view.password_confirmation') %>
      <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Confirm password" %>
    </div>
    <div class="form-check">
      <%= f.check_box :admin, class: "form-check-input" %>
      <%= f.label :admin, class: "form-check-label" %>
    </div>
    <div class="form-group mt-3">
      <%= f.submit "Register", class: "btn btn-info" %>
    </div>
    <% end %>
  </div>
</div>
<div class="col-md-5">
</div>

app/views/admin/users/show.html.erb
<div class="col-md-1">
</div>
<div class="col-xs-12 col-md-11">
  <h1>Managment details</h1>
  <div class="card mt-3" style="width: 30rem;" >
    <div class="card-header">
      <h2><%= @user.user_name %>'s page</h2>
    </div>
    <div class="card-body">
      <p>email：<%= @user.email %></p>
    </div>
    <div class="list-group list-group-flush">
      <div class="list-group-item">
        <p>Tasks register ：<%= @user.tasks.count %></p>
        <%= link_to "Task List", tasks_path, class: "btn btn-light" %>
      </div>
    </div>
  </div>
</div>