config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
  end
  root to: 'tasks#index'
  resources :tasks, :labels
  resources :users, only: %i[ new show edit create destroy ]
  resources :sessions, only: %i[ new create destroy ]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mayo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="sticky-top">
      <div class="container-fluid">
        <div class="row justify-content-between ">
          <div class="col-xs-12 col-md-2 ">
          </div>
          <div class="d-flex bd-highlight">
            <div class="mt-1 p-3 bd-highlight align-self-center">
              <% if logged_in? %>
                <%= link_to "Profile", user_path(current_user.id), id: "header_btns", class: "justify-content-around btn btn-outline" %>
                <%= link_to "Logout", session_path(current_user.id), method: :delete, id: "header_btns", class: "justify-content-around btn btn-outline" %>
                <% if current_user.admin? %>
                  <%= link_to "User List ", admin_users_path, id: "header_btns", class: "justify-content-around btn btn-outline" %>
                <% end %>
              <% else %>
                <%= link_to "Sign up", new_user_path, id: "header_btns", class: "justify-content-around btn btn-outline" %>
                <%= link_to "Login", new_session_path, id: "header_btns", class: "justify-content-around btn btn-outline" %>
              <% end %>
            </div>
          </div>
          <div class="col-xs-12 col-md-2">
          </div>
        </div>
      </div>
    </header>
    <div class="container-fluid">
      <div class="align-self-start" id="flash">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      </div>
      <div class="bd-highlight align-self-center">
      <%= yield %>
      </div>
      <div class="align-self-end">
      </div>
    </div>
  </body>
</html>